// animalOptions.js
export const animalOptions = [
  { value: 'dog', label: 'Dog' },
  { value: 'cat', label: 'Cat' },
  { value: 'goat', label: 'Goat' },
  { value: 'parrot', label: 'Parrot' },
  { value: 'pig', label: 'Pig' },
  { value: 'guinea-pig', label: 'Guinea Pig' },
  { value: 'budgerigar', label: 'Budgerigar' },
  { value: 'rabbit', label: 'Rabbit' },
  { value: 'duck', label: 'Duck' },
  { value: 'tarantulas', label: 'Tarantulas' },
  { value: 'raccoon', label: 'Raccoon' },
  { value: 'fish', label: 'Fish' },
  { value: 'monkey', label: 'Monkey' },
  { value: 'horse', label: 'Horse' },
  { value: 'turtle', label: 'Turtle' },
  { value: 'ferret', label: 'Ferret' },
  { value: 'chinchilla', label: 'Chinchilla' },
  { value: 'snake', label: 'Snake' },
  { value: 'gecko', label: 'Gecko' },
  { value: 'frog', label: 'Frog' },
  { value: 'hamster', label: 'Hamster' },
  { value: 'hedgehog', label: 'Hedgehog' },
  { value: 'iguana', label: 'Iguana' },
  { value: 'parakeet', label: 'Parakeet' },
  { value: 'canary', label: 'Canary' },
  { value: 'cockatiel', label: 'Cockatiel' },
  { value: 'lizard', label: 'Lizard' },
  { value: 'squirrel', label: 'Squirrel' },
  { value: 'bearded-dragon', label: 'Bearded Dragon' },
  { value: 'cavy', label: 'Cavy (Guinea Pig)' },
  { value: 'tarpon', label: 'Tarpon' },
  { value: 'axolotl', label: 'Axolotl' },
  { value: 'bat', label: 'Bat' },
  { value: 'armadillo', label: 'Armadillo' },
  { value: 'cheetah', label: 'Cheetah' },
  { value: 'kangaroo', label: 'Kangaroo' },
  { value: 'sloth', label: 'Sloth' },
  { value: 'bison', label: 'Bison' },
  { value: 'zebra', label: 'Zebra' },
  { value: 'bald-eagle', label: 'Bald Eagle' },
  { value: 'penguin', label: 'Penguin' },
  { value: 'koala', label: 'Koala' },
  { value: 'wombat', label: 'Wombat' },
];
